pipeline {
    agent {
        docker {
            image 'node:12.2.0'
            args '-p 3000:3000'
            args '-u root:root'
            
        }
    }
    environment {
        NPM_CONFIG_CACHE = "${WORKSPACE}/.npm"
    }
    stages {
        stage('checkout'){
            steps{
                script{
                    checkout([$class: 'GitSCM', branches: [[name: '*/master']], extensions: [], userRemoteConfigs: [[credentialsId: 'bitbucket-cred', url: 'https://ab-aritrab@bitbucket.org/arpiantech_animesh/ag-grid-react-example.git']]])
                }
            }
        }
        stage('Build') {
            steps {
                sh 'rm -rf node_modules'
                sh 'rm -f package-lock.json'
                sh 'rm -rf dist'
                sh 'npm install --unsafe-perm=true --allow-root'
                sh 'export PATH=$PWD/node_modules/.bin:$PATH'
                sh 'npm run build'
            }
        }
        // stage('Test') {
        //     steps {
        //         sh './jenkins/scripts/test.sh'
        //     }
        // }
        // stage('Deliver') {
        //     steps {
        //         sh './jenkins/scripts/deliver.sh'
        //         input message: 'Finished using the web site? (Click "Proceed" to continue)'
        //         sh './jenkins/scripts/kill.sh'
        //     }
        // }
    }
}

// checkout([$class: 'GitSCM', branches: [[name: '*/master']], extensions: [], userRemoteConfigs: [[url: 'https://github.com/jenkins-docs/simple-node-js-react-npm-app.git']]])